radarr:
  radarr:
    base_url: http://localhost:7878
    delete_old_custom_formats: true
    api_key: !env_var RADARR_API_KEY
    include:
    - template: radarr-quality-definition-movie
    - config: /etc/recyclarr-config/radarr/general-cfs.yml
    - config: /etc/recyclarr-config/radarr/general-qp.yml
    - config: /etc/recyclarr-config/radarr/anime-cfs.yml
    - config: /etc/recyclarr-config/radarr/anime-qp.yml
    media_naming:
      folder: default
      movie:
        rename: true
        standard: anime
    replace_existing_custom_formats: true
sonarr:
  sonarr:
    base_url: http://localhost:8989
    delete_old_custom_formats: true
    api_key: !env_var SONARR_API_KEY
    include:
    - template: sonarr-quality-definition-series
    - template: sonarr-quality-definition-anime
    - config: /etc/recyclarr-config/sonarr/general-cfs.yml
    - config: /etc/recyclarr-config/sonarr/general-qp.yml
    - config: /etc/recyclarr-config/sonarr/anime-cfs.yml
    - config: /etc/recyclarr-config/sonarr/anime-qp.yml
    media_naming:
      episodes:
        anime: no-episode-title
        daily: no-episode-title
        rename: true
        standard: no-episode-title
      season: default
      series: default
    replace_existing_custom_formats: true