keys:
  - &truelecter A35AABA719FAC1A001E375F8EEF7F5B1C5AB1F74

  - &squadbook age1zltjqzpr3du45xnsy85q80nafejrvhlat2ugs8pysf763fm6spxsjk29eg
  - &tl-wsl    age1qmurstgayt65a8r7j9nnf9mpz7wffxht2j8uadxy9pupylrqscyqv5m7zk
  - &depsos    age17k6xap8v8ys080dx5jen9pycnkzjrdgnxzyqyv0lz34auspg4g8qykuuev
  - &oracle    age1yk5h5m3uqzsedlc433n0p2aph6cdvuxvvr9nrrr3mtzmj22k3vmqp7ndhy
  - &voron     age1q56y2fganxr7af2tel0pcpzueps4ttlyja3ysxxrtq5cs9cmr57q5e3fwf
  - &nas       age12d0vn4m8dygjjjgx8s5zdm0lkk6qfcyk35u9lgj6d6cw7753gs0s049uz9
  - &sirius    age1vpflrapt4lz5akw8jcft6lhhq0h26ptjq6ce8da27gzuvfdmtqvs8rk8h6
  - &vzbot235  age1whtmnnc0ar8u0htwayr4qkukeyq05jt397prfzkkak0aec29ystsyfzdkt
  - &tinym     age1ygjayuhd3sx0xnxlxuhftz0qj79j95x4cewfj2e5ux9k7f335v2sul9u97
  - &bttpi     age1pcvq86sasvxdqceyjcgxr7lppugasqsfdwt3ewnlufn9xyel5u8qeu0hn5
  - &tl-mm4    age13xs4xvwm0ythks33uvgv7v9gnqhn9mvhqgyzg8u94060pxjc3urq3ht6r8

creation_rules:
  - path_regex: secrets/minecraft-server.yaml
    key_groups:
      - pgp:
          - *truelecter
        age:
          - *oracle

  - path_regex: secrets/nixos-common.yaml
    key_groups:
      - pgp:
          - *truelecter
        age:
          - *nas
          - *depsos
          - *oracle
          - *tl-wsl
          - *voron
          - *sirius
          - *vzbot235
          - *tinym
          - *bttpi
          - *tl-mm4

  - path_regex: secrets/bots/.*
    key_groups:
      - pgp:
          - *truelecter
        age:
          - *depsos

  - path_regex: secrets/wireguard.yaml
    key_groups:
      - pgp:
          - *truelecter
        age:
          - *depsos

  - path_regex: secrets/wifi.yaml
    key_groups:
      - pgp:
          - *truelecter
        age:
          - *squadbook
          - *voron
          - *nas
          - *sirius
          - *vzbot235
          - *tinym
          - *bttpi
          - *tl-mm4

  - path_regex: secrets/ssh/remote-builder$
    key_groups:
      - pgp:
          - *truelecter
        age:
          - *squadbook
          - *tl-wsl
          - *tl-mm4