keys:
  - &truelecter A35AABA719FAC1A001E375F8EEF7F5B1C5AB1F74
  - &server-nas 70732b3ee3a1c10a8b6b849a959a413b28c00df9

creation_rules:
  - path_regex: secrets/sops/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *truelecter
      - *server-nas
