# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  camera-streamer = {
    pname = "camera-streamer";
    version = "de94871d91daac5f16b550856bf286129a099f1d";
    src = fetchFromGitHub {
      owner = "mryel00";
      repo = "camera-streamer";
      rev = "de94871d91daac5f16b550856bf286129a099f1d";
      fetchSubmodules = true;
      sha256 = "sha256-Gz8NArht3sU9DGzL3geLYfc+ZNt/pLVJca6Q/kiCzmc=";
    };
    date = "2025-12-05";
  };
  experimental-kalico = {
    pname = "experimental-kalico";
    version = "107302c468c2e692e7bcb1e8c66032782c4ad555";
    src = fetchFromGitHub {
      owner = "KalicoCrew";
      repo = "kalico";
      rev = "107302c468c2e692e7bcb1e8c66032782c4ad555";
      fetchSubmodules = false;
      sha256 = "sha256-hNH6bFgSI3xIJQx5M1o7h5SMSP09mLdJwDmZtEn0p/E=";
    };
    date = "2026-01-04";
  };
  kalico = {
    pname = "kalico";
    version = "4a173af8f5f0170ecfefb885e64e7f711e5323f7";
    src = fetchFromGitHub {
      owner = "KalicoCrew";
      repo = "kalico";
      rev = "4a173af8f5f0170ecfefb885e64e7f711e5323f7";
      fetchSubmodules = false;
      sha256 = "sha256-mvgJDHxwQQyOYbEgNKMNUpd9P100JVdsx0ggQGLp+yU=";
    };
    date = "2026-01-22";
  };
  katapult = {
    pname = "katapult";
    version = "b0bf421069e2aab810db43d6e15f38817d981451";
    src = fetchFromGitHub {
      owner = "Arksine";
      repo = "katapult";
      rev = "b0bf421069e2aab810db43d6e15f38817d981451";
      fetchSubmodules = false;
      sha256 = "sha256-3b2PQfxb1jZtHM61QqHEGGBjljLfYqPEcJ95Sf3xCsg=";
    };
    date = "2025-11-15";
  };
  klipper = {
    pname = "klipper";
    version = "48f0b3cad6d4593746384bf49a39913dcb8cc796";
    src = fetchFromGitHub {
      owner = "Klipper3d";
      repo = "klipper";
      rev = "48f0b3cad6d4593746384bf49a39913dcb8cc796";
      fetchSubmodules = false;
      sha256 = "sha256-96o3Fa+VMVdf6mbC/XLpATzT7v27g6bxWLaSYM7nZ1g=";
    };
    date = "2026-01-11";
  };
  klipper-cartographer = {
    pname = "klipper-cartographer";
    version = "07ca934e05b15cc1294843fb84bf01d3fa6644c3";
    src = fetchFromGitHub {
      owner = "Cartographer3D";
      repo = "cartographer-klipper";
      rev = "07ca934e05b15cc1294843fb84bf01d3fa6644c3";
      fetchSubmodules = false;
      sha256 = "sha256-QQLTqxS3gU0zrXqjqbfgNq1sRiPr/fvddI6KHeRe6uU=";
    };
    date = "2025-10-07";
  };
  klipper-cartographer-plugin = {
    pname = "klipper-cartographer-plugin";
    version = "v1.3.3";
    src = fetchFromGitHub {
      owner = "Cartographer3D";
      repo = "cartographer3d-plugin";
      rev = "v1.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-87YGaXQhUmXw4jPYiRv/mZlIyY4L2SOLhljbFIPU7/Y=";
    };
  };
  klipper-chopper-resonance-tuner = {
    pname = "klipper-chopper-resonance-tuner";
    version = "1f98212ca9dbfdf15d516115dd4c26e97b914a8d";
    src = fetchFromGitHub {
      owner = "MRX8024";
      repo = "chopper-resonance-tuner";
      rev = "1f98212ca9dbfdf15d516115dd4c26e97b914a8d";
      fetchSubmodules = false;
      sha256 = "sha256-KLWWjHgEmQ9yJD6uUgjYieY8S1Td1qB5SaWN1znAGDk=";
    };
    date = "2024-08-23";
  };
  klipper-ercf = {
    pname = "klipper-ercf";
    version = "fb9a6c7daaf881ab507368386e733a800b26f595";
    src = fetchFromGitHub {
      owner = "EtteGit";
      repo = "EnragedRabbitProject";
      rev = "fb9a6c7daaf881ab507368386e733a800b26f595";
      fetchSubmodules = false;
      sha256 = "sha256-Gwi0HiCIlTBQkHlFnmG0sZWB2xA1y5maJxF7VdfQMxU=";
    };
    date = "2022-09-02";
  };
  klipper-gcode_shell_command = {
    pname = "klipper-gcode_shell_command";
    version = "80948edbb48b4ab1aad5213ba7c28e61af055dc8";
    src = fetchFromGitHub {
      owner = "dw-0";
      repo = "kiauh";
      rev = "80948edbb48b4ab1aad5213ba7c28e61af055dc8";
      fetchSubmodules = false;
      sha256 = "sha256-7km5KXun8nWFO615ch/RjtJo4pRxbGa9k8X+KLzg1N0=";
    };
    date = "2026-01-19";
  };
  klipper-happy-hare = {
    pname = "klipper-happy-hare";
    version = "76eca598d7301d6e834ed39068e83270d318afff";
    src = fetchFromGitHub {
      owner = "moggieuk";
      repo = "Happy-Hare";
      rev = "76eca598d7301d6e834ed39068e83270d318afff";
      fetchSubmodules = false;
      sha256 = "sha256-NbsTCULm+odEqR8XHY6xHqrBIoFXNwbn6ScP36Sm5g8=";
    };
    date = "2026-01-22";
  };
  klipper-kamp = {
    pname = "klipper-kamp";
    version = "v1.1.2";
    src = fetchFromGitHub {
      owner = "kyleisah";
      repo = "Klipper-Adaptive-Meshing-Purging";
      rev = "v1.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-anBGjLtYlyrxeNVy1TEMcAGTVUFrGClLuoJZuo3xlDM=";
    };
  };
  klipper-klicky-probe = {
    pname = "klipper-klicky-probe";
    version = "ab86f91d47ac7353a0a7c7e0de26542dca00f63e";
    src = fetchFromGitHub {
      owner = "jlas1";
      repo = "Klicky-Probe";
      rev = "ab86f91d47ac7353a0a7c7e0de26542dca00f63e";
      fetchSubmodules = false;
      sha256 = "sha256-FKIBQnvDJdvgwPL3ekgx/6QbHPRuObEG307dlFk/fbY=";
    };
    date = "2025-02-10";
  };
  klipper-klippain-shaketune = {
    pname = "klipper-klippain-shaketune";
    version = "354ee4be6db218715239f7b9411c2c37fdea23dd";
    src = fetchFromGitHub {
      owner = "Frix-x";
      repo = "klippain-shaketune";
      rev = "354ee4be6db218715239f7b9411c2c37fdea23dd";
      fetchSubmodules = false;
      sha256 = "sha256-ztgLp8PUJafUBt/PdlGj5x7ER5vxw4uIfh3/3Cbl8Ps=";
    };
    date = "2026-01-16";
  };
  klipper-led_effect = {
    pname = "klipper-led_effect";
    version = "24d26c7208c7260a528b4438c7dbf0c279968c01";
    src = fetchFromGitHub {
      owner = "julianschill";
      repo = "klipper-led_effect";
      rev = "24d26c7208c7260a528b4438c7dbf0c279968c01";
      fetchSubmodules = false;
      sha256 = "sha256-Mv+xjT43SlP1x8tJ7ksfKdd2wfN2KZ4ydJmnjCj4V1M=";
    };
    date = "2026-01-23";
  };
  klipper-nevermore-controller = {
    pname = "klipper-nevermore-controller";
    version = "6c627d9b8bcd5dacdca27f335a5ccfb8a7093fbd";
    src = fetchFromGitHub {
      owner = "SanaaHamel";
      repo = "nevermore-controller";
      rev = "6c627d9b8bcd5dacdca27f335a5ccfb8a7093fbd";
      fetchSubmodules = false;
      sha256 = "sha256-O0Zkb7+mL5jFn8z+4pPyou7KqgW0v/1K4NpQuhxbHAU=";
    };
    date = "2025-11-02";
  };
  klipper-nevermore-max = {
    pname = "klipper-nevermore-max";
    version = "159df10e4f6015680107d1cbd10a3aab23dd5f18";
    src = fetchFromGitHub {
      owner = "nevermore3d";
      repo = "Nevermore_Max";
      rev = "159df10e4f6015680107d1cbd10a3aab23dd5f18";
      fetchSubmodules = false;
      sha256 = "sha256-uPTUlI2F697pDPw5HxU48dEUpBkgovb61ksXW1HRfLY=";
    };
    date = "2023-11-18";
  };
  klipper-screen = {
    pname = "klipper-screen";
    version = "3fb5a031a4ec0a7491f3e22509c8bc411f89db5c";
    src = fetchFromGitHub {
      owner = "jordanruthe";
      repo = "KlipperScreen";
      rev = "3fb5a031a4ec0a7491f3e22509c8bc411f89db5c";
      fetchSubmodules = false;
      sha256 = "sha256-BrfGKADzJM55jZqCDPxxG+QE1ZQ3uyygx3zDwm+9lPE=";
    };
    date = "2026-01-17";
  };
  klipper-z-calibration = {
    pname = "klipper-z-calibration";
    version = "v1.1.3";
    src = fetchFromGitHub {
      owner = "protoloft";
      repo = "klipper_z_calibration";
      rev = "v1.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-WWP0LqhJ3ET4nxR8hVpq1uMOSK+CX7f3LXjOAZbRY8c=";
    };
  };
  klipper_tmc_autotune = {
    pname = "klipper_tmc_autotune";
    version = "9d86496e188bb338febcc117efc9d8b665ae1c7a";
    src = fetchFromGitHub {
      owner = "andrewmcgr";
      repo = "klipper_tmc_autotune";
      rev = "9d86496e188bb338febcc117efc9d8b665ae1c7a";
      fetchSubmodules = false;
      sha256 = "sha256-YB6VFSH69Q50LwsFII6hFIxVt0loESEFNAr0W/RJ4WY=";
    };
    date = "2026-01-16";
  };
  libdatachannel_latest = {
    pname = "libdatachannel_latest";
    version = "a4d3211da33bc1114ae50d2dd12f4186b67aaba4";
    src = fetchFromGitHub {
      owner = "paullouisageneau";
      repo = "libdatachannel";
      rev = "a4d3211da33bc1114ae50d2dd12f4186b67aaba4";
      fetchSubmodules = true;
      sha256 = "sha256-gOMwS/nkbyYzu8KmEXD1kbU8C3fj2eKTMi0KpR8oVsw=";
    };
    date = "2026-01-20";
  };
  libjuice = {
    pname = "libjuice";
    version = "v1.6.2";
    src = fetchFromGitHub {
      owner = "paullouisageneau";
      repo = "libjuice";
      rev = "v1.6.2";
      fetchSubmodules = false;
      sha256 = "sha256-i+Hx0Qg9g35L5gg5OMVnitmQ84BnE+0IDXdvrLLdz8Y=";
    };
  };
  live555 = {
    pname = "live555";
    version = "2020.03.06";
    src = fetchTarball {
      url = "https://download.videolan.org/pub/contrib/live555/live.2020.03.06.tar.gz";
      sha256 = "sha256-UxunbrJC6UVlwexso/cuH9m+mUSf7WEPMLincUrqDWE=";
    };
  };
  mainsail = {
    pname = "mainsail";
    version = "20ee3e43014109cca8acd7615f088ee942083cdd";
    src = fetchFromGitHub {
      owner = "mainsail-crew";
      repo = "mainsail";
      rev = "20ee3e43014109cca8acd7615f088ee942083cdd";
      fetchSubmodules = false;
      sha256 = "sha256-cRmF8x6phQb3ousoxHmb4HEFKCHBkF0cX21bBMrWF6A=";
    };
    date = "2026-01-19";
  };
  mobileraker-companion = {
    pname = "mobileraker-companion";
    version = "1e866ae25278d574d38e779c1a31a9780a130761";
    src = fetchFromGitHub {
      owner = "Clon1998";
      repo = "mobileraker_companion";
      rev = "1e866ae25278d574d38e779c1a31a9780a130761";
      fetchSubmodules = false;
      sha256 = "sha256-RcMe/KSN72RUXXGiDkumRIyoXsn0RGRDRZk9mAZCZTU=";
    };
    date = "2026-01-10";
  };
  moonraker = {
    pname = "moonraker";
    version = "3e29720cb2ac8c5679c2085849f344f33f089be4";
    src = fetchFromGitHub {
      owner = "Arksine";
      repo = "moonraker";
      rev = "3e29720cb2ac8c5679c2085849f344f33f089be4";
      fetchSubmodules = false;
      sha256 = "sha256-fzdqozm48wBMGwGLH5KaIuEVDI1YHPNJdK5u0Ec+y2c=";
    };
    date = "2026-01-22";
  };
  python-networkmanager = {
    pname = "python-networkmanager";
    version = "2.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/python-networkmanager/python-networkmanager-2.2.tar.gz";
      sha256 = "sha256-3m65IdlKunVJ9CjtKzqkgqXVQ+y2lly6oPu1VasxudU=";
    };
  };
  python-scheduler = {
    pname = "python-scheduler";
    version = "0.8.8";
    src = fetchurl {
      url = "https://pypi.org/packages/source/s/scheduler/scheduler-0.8.8.tar.gz";
      sha256 = "sha256-RXWhLNJp5OSJZAmDb9kRVgy2P7djQ2DuYqovpOxJX/0=";
    };
  };
  python-sqlalchemy-cockroachdb = {
    pname = "python-sqlalchemy-cockroachdb";
    version = "2.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/s/sqlalchemy-cockroachdb/sqlalchemy-cockroachdb-2.0.2.tar.gz";
      sha256 = "sha256-EZdW65BYVdahE0W5nP6FMDGj/lmKnEvzWo3ayfif6Mw=";
    };
  };
  spoolman = {
    pname = "spoolman";
    version = "v0.23.0";
    src = fetchurl {
      url = "https://github.com/Donkie/Spoolman/releases/download/v0.23.0/spoolman.zip";
      sha256 = "sha256-Y6UBqhHICXnD2JyL2M4mEzqTXAsSNEdbbnATeyS2qzk=";
    };
  };
}
