# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  camera-streamer = {
    pname = "camera-streamer";
    version = "e17a86e4f9bd0fda4bd901f14a5e2eef682962f8";
    src = fetchFromGitHub {
      owner = "mryel00";
      repo = "camera-streamer";
      rev = "e17a86e4f9bd0fda4bd901f14a5e2eef682962f8";
      fetchSubmodules = true;
      sha256 = "sha256-umU8Rp8+wUvQCNK8OpgND/6gPD013SB6sdXSLy5UGAQ=";
    };
    date = "2026-03-02";
  };
  experimental-kalico = {
    pname = "experimental-kalico";
    version = "107302c468c2e692e7bcb1e8c66032782c4ad555";
    src = fetchFromGitHub {
      owner = "KalicoCrew";
      repo = "kalico";
      rev = "107302c468c2e692e7bcb1e8c66032782c4ad555";
      fetchSubmodules = false;
      sha256 = "sha256-hNH6bFgSI3xIJQx5M1o7h5SMSP09mLdJwDmZtEn0p/E=";
    };
    date = "2026-01-04";
  };
  kalico = {
    pname = "kalico";
    version = "588ea2d14e0e76b426434c887ac71bcf570369d8";
    src = fetchFromGitHub {
      owner = "KalicoCrew";
      repo = "kalico";
      rev = "588ea2d14e0e76b426434c887ac71bcf570369d8";
      fetchSubmodules = false;
      sha256 = "sha256-oARIkpQCc5YtjDeCzrhx+ebVrbumgSwuDwNhIkJACN4=";
    };
    date = "2026-04-10";
  };
  katapult = {
    pname = "katapult";
    version = "ec59b9bb9ad6c2ec8d4dc6831fbc77f0b308e29e";
    src = fetchFromGitHub {
      owner = "Arksine";
      repo = "katapult";
      rev = "ec59b9bb9ad6c2ec8d4dc6831fbc77f0b308e29e";
      fetchSubmodules = false;
      sha256 = "sha256-iQ/z1qWWopb6wG1lHLL/nxrSCBmcdW20k66rpAYpN6Y=";
    };
    date = "2026-03-20";
  };
  klipper = {
    pname = "klipper";
    version = "35ace52976e1ef8c00da9477d583cab610d70d1c";
    src = fetchFromGitHub {
      owner = "Klipper3d";
      repo = "klipper";
      rev = "35ace52976e1ef8c00da9477d583cab610d70d1c";
      fetchSubmodules = false;
      sha256 = "sha256-sSyRamAQ8UGyrb80hGac1xuiDe0xsjqb4q//jiGpVTk=";
    };
    date = "2026-04-09";
  };
  klipper-cartographer = {
    pname = "klipper-cartographer";
    version = "d8fbed79a8f5be18a7bae27decf727843f768e09";
    src = fetchFromGitHub {
      owner = "Cartographer3D";
      repo = "cartographer-klipper";
      rev = "d8fbed79a8f5be18a7bae27decf727843f768e09";
      fetchSubmodules = false;
      sha256 = "sha256-jX3Cx+GW9OijTyMCMycb0eK42MRW0vknGz97up8ik3E=";
    };
    date = "2026-03-19";
  };
  klipper-cartographer-plugin = {
    pname = "klipper-cartographer-plugin";
    version = "v1.5.1";
    src = fetchFromGitHub {
      owner = "Cartographer3D";
      repo = "cartographer3d-plugin";
      rev = "v1.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-ruLIvt8L1fJcXQlP4gb+7SXKJKxs0juuhWs6TitcPA4=";
    };
  };
  klipper-chopper-resonance-tuner = {
    pname = "klipper-chopper-resonance-tuner";
    version = "1f98212ca9dbfdf15d516115dd4c26e97b914a8d";
    src = fetchFromGitHub {
      owner = "MRX8024";
      repo = "chopper-resonance-tuner";
      rev = "1f98212ca9dbfdf15d516115dd4c26e97b914a8d";
      fetchSubmodules = false;
      sha256 = "sha256-KLWWjHgEmQ9yJD6uUgjYieY8S1Td1qB5SaWN1znAGDk=";
    };
    date = "2024-08-23";
  };
  klipper-ercf = {
    pname = "klipper-ercf";
    version = "fb9a6c7daaf881ab507368386e733a800b26f595";
    src = fetchFromGitHub {
      owner = "EtteGit";
      repo = "EnragedRabbitProject";
      rev = "fb9a6c7daaf881ab507368386e733a800b26f595";
      fetchSubmodules = false;
      sha256 = "sha256-Gwi0HiCIlTBQkHlFnmG0sZWB2xA1y5maJxF7VdfQMxU=";
    };
    date = "2022-09-02";
  };
  klipper-gcode_shell_command = {
    pname = "klipper-gcode_shell_command";
    version = "09a5d96b6339b9f0477b1dc58daadaf411e55416";
    src = fetchFromGitHub {
      owner = "dw-0";
      repo = "kiauh";
      rev = "09a5d96b6339b9f0477b1dc58daadaf411e55416";
      fetchSubmodules = false;
      sha256 = "sha256-vXCmvLhMRl0G/EA/MlD66Nai4KgrAtoSf25C6BE2FyA=";
    };
    date = "2026-02-03";
  };
  klipper-happy-hare = {
    pname = "klipper-happy-hare";
    version = "a880ac0adccf532cf98a20567c47e10efdee5576";
    src = fetchFromGitHub {
      owner = "moggieuk";
      repo = "Happy-Hare";
      rev = "a880ac0adccf532cf98a20567c47e10efdee5576";
      fetchSubmodules = false;
      sha256 = "sha256-Aq+PpKZmZH2Gr08EycfPGi5pTrscRjmOX4kN5/VitCk=";
    };
    date = "2026-02-28";
  };
  klipper-kamp = {
    pname = "klipper-kamp";
    version = "v1.1.2";
    src = fetchFromGitHub {
      owner = "kyleisah";
      repo = "Klipper-Adaptive-Meshing-Purging";
      rev = "v1.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-anBGjLtYlyrxeNVy1TEMcAGTVUFrGClLuoJZuo3xlDM=";
    };
  };
  klipper-klicky-probe = {
    pname = "klipper-klicky-probe";
    version = "ab86f91d47ac7353a0a7c7e0de26542dca00f63e";
    src = fetchFromGitHub {
      owner = "jlas1";
      repo = "Klicky-Probe";
      rev = "ab86f91d47ac7353a0a7c7e0de26542dca00f63e";
      fetchSubmodules = false;
      sha256 = "sha256-FKIBQnvDJdvgwPL3ekgx/6QbHPRuObEG307dlFk/fbY=";
    };
    date = "2025-02-10";
  };
  klipper-klippain-shaketune = {
    pname = "klipper-klippain-shaketune";
    version = "354ee4be6db218715239f7b9411c2c37fdea23dd";
    src = fetchFromGitHub {
      owner = "Frix-x";
      repo = "klippain-shaketune";
      rev = "354ee4be6db218715239f7b9411c2c37fdea23dd";
      fetchSubmodules = false;
      sha256 = "sha256-ztgLp8PUJafUBt/PdlGj5x7ER5vxw4uIfh3/3Cbl8Ps=";
    };
    date = "2026-01-16";
  };
  klipper-led_effect = {
    pname = "klipper-led_effect";
    version = "266f1049c7172c2fba0da4a52314dcfc0c3bb56f";
    src = fetchFromGitHub {
      owner = "julianschill";
      repo = "klipper-led_effect";
      rev = "266f1049c7172c2fba0da4a52314dcfc0c3bb56f";
      fetchSubmodules = false;
      sha256 = "sha256-ZGYk1Qdm7GFEiS7xepjqIlo1L/AZZKEEIOWdG9UA+4I=";
    };
    date = "2026-03-16";
  };
  klipper-nevermore-controller = {
    pname = "klipper-nevermore-controller";
    version = "6c627d9b8bcd5dacdca27f335a5ccfb8a7093fbd";
    src = fetchFromGitHub {
      owner = "SanaaHamel";
      repo = "nevermore-controller";
      rev = "6c627d9b8bcd5dacdca27f335a5ccfb8a7093fbd";
      fetchSubmodules = false;
      sha256 = "sha256-O0Zkb7+mL5jFn8z+4pPyou7KqgW0v/1K4NpQuhxbHAU=";
    };
    date = "2025-11-02";
  };
  klipper-nevermore-max = {
    pname = "klipper-nevermore-max";
    version = "159df10e4f6015680107d1cbd10a3aab23dd5f18";
    src = fetchFromGitHub {
      owner = "nevermore3d";
      repo = "Nevermore_Max";
      rev = "159df10e4f6015680107d1cbd10a3aab23dd5f18";
      fetchSubmodules = false;
      sha256 = "sha256-uPTUlI2F697pDPw5HxU48dEUpBkgovb61ksXW1HRfLY=";
    };
    date = "2023-11-18";
  };
  klipper-screen = {
    pname = "klipper-screen";
    version = "056831910087a858908f9f5d117ad5c50446e729";
    src = fetchFromGitHub {
      owner = "jordanruthe";
      repo = "KlipperScreen";
      rev = "056831910087a858908f9f5d117ad5c50446e729";
      fetchSubmodules = false;
      sha256 = "sha256-oao7zWftYwLv4Qz9CC0oVbXTeyG19WofIQ6rk3/82u0=";
    };
    date = "2026-04-05";
  };
  klipper-z-calibration = {
    pname = "klipper-z-calibration";
    version = "v1.1.3";
    src = fetchFromGitHub {
      owner = "protoloft";
      repo = "klipper_z_calibration";
      rev = "v1.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-WWP0LqhJ3ET4nxR8hVpq1uMOSK+CX7f3LXjOAZbRY8c=";
    };
  };
  klipper_tmc_autotune = {
    pname = "klipper_tmc_autotune";
    version = "f366d75fa44d177aa6fb002cdff50195e6952772";
    src = fetchFromGitHub {
      owner = "andrewmcgr";
      repo = "klipper_tmc_autotune";
      rev = "f366d75fa44d177aa6fb002cdff50195e6952772";
      fetchSubmodules = false;
      sha256 = "sha256-EA4hmIQ7RsSfb+2s/TL2bp2yug3ZdefMGlWNs7fem+Y=";
    };
    date = "2026-03-25";
  };
  libdatachannel_latest = {
    pname = "libdatachannel_latest";
    version = "9ddf88971fcc7437b2bfeef92ba5454b7de067f8";
    src = fetchFromGitHub {
      owner = "paullouisageneau";
      repo = "libdatachannel";
      rev = "9ddf88971fcc7437b2bfeef92ba5454b7de067f8";
      fetchSubmodules = true;
      sha256 = "sha256-e2AfDmOAKOgcaePHFOIzKEsC/XxVz+1J1JZv56Dfsoo=";
    };
    date = "2026-04-06";
  };
  libjuice = {
    pname = "libjuice";
    version = "v1.6.2";
    src = fetchFromGitHub {
      owner = "paullouisageneau";
      repo = "libjuice";
      rev = "v1.6.2";
      fetchSubmodules = false;
      sha256 = "sha256-i+Hx0Qg9g35L5gg5OMVnitmQ84BnE+0IDXdvrLLdz8Y=";
    };
  };
  live555 = {
    pname = "live555";
    version = "2020.03.06";
    src = fetchTarball {
      url = "https://download.videolan.org/pub/contrib/live555/live.2020.03.06.tar.gz";
      sha256 = "sha256-UxunbrJC6UVlwexso/cuH9m+mUSf7WEPMLincUrqDWE=";
    };
  };
  mainsail = {
    pname = "mainsail";
    version = "b391df5e79e3356cb0d2dead854af921933e04bd";
    src = fetchFromGitHub {
      owner = "mainsail-crew";
      repo = "mainsail";
      rev = "b391df5e79e3356cb0d2dead854af921933e04bd";
      fetchSubmodules = false;
      sha256 = "sha256-j6eHdvyC9ERXQZfXu/RWl1QCXDgh3U2KkHpr9H3pD6s=";
    };
    date = "2026-04-04";
  };
  mobileraker-companion = {
    pname = "mobileraker-companion";
    version = "1e866ae25278d574d38e779c1a31a9780a130761";
    src = fetchFromGitHub {
      owner = "Clon1998";
      repo = "mobileraker_companion";
      rev = "1e866ae25278d574d38e779c1a31a9780a130761";
      fetchSubmodules = false;
      sha256 = "sha256-RcMe/KSN72RUXXGiDkumRIyoXsn0RGRDRZk9mAZCZTU=";
    };
    date = "2026-01-10";
  };
  moonraker = {
    pname = "moonraker";
    version = "1ed102edfb34906115bfeb02712d4c839b93a7a9";
    src = fetchFromGitHub {
      owner = "Arksine";
      repo = "moonraker";
      rev = "1ed102edfb34906115bfeb02712d4c839b93a7a9";
      fetchSubmodules = false;
      sha256 = "sha256-d6gDym5d/c3CKI5vcyljlQJvbdZbKTOQQV/YrQAunmU=";
    };
    date = "2026-03-23";
  };
  python-networkmanager = {
    pname = "python-networkmanager";
    version = "2.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/python-networkmanager/python-networkmanager-2.2.tar.gz";
      sha256 = "sha256-3m65IdlKunVJ9CjtKzqkgqXVQ+y2lly6oPu1VasxudU=";
    };
  };
  python-scheduler = {
    pname = "python-scheduler";
    version = "0.8.11";
    src = fetchurl {
      url = "https://pypi.org/packages/source/s/scheduler/scheduler-0.8.11.tar.gz";
      sha256 = "sha256-siNKBpRIphervFEbnhj0jE3rPc2dzFFyHZyQ7ylDtyo=";
    };
  };
  python-sqlalchemy-cockroachdb = {
    pname = "python-sqlalchemy-cockroachdb";
    version = "2.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/s/sqlalchemy-cockroachdb/sqlalchemy-cockroachdb-2.0.2.tar.gz";
      sha256 = "sha256-EZdW65BYVdahE0W5nP6FMDGj/lmKnEvzWo3ayfif6Mw=";
    };
  };
  spoolman = {
    pname = "spoolman";
    version = "v0.23.1";
    src = fetchurl {
      url = "https://github.com/Donkie/Spoolman/releases/download/v0.23.1/spoolman.zip";
      sha256 = "sha256-v64qELJ33WdKvZ7+yFwELI1vRwChVa+VHAlg2z9iYYU=";
    };
  };
}
