# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  camera-streamer = {
    pname = "camera-streamer";
    version = "d4a8ea98a57b6b199ca405dd656e19efe3e62fed";
    src = fetchFromGitHub {
      owner = "mryel00";
      repo = "camera-streamer";
      rev = "d4a8ea98a57b6b199ca405dd656e19efe3e62fed";
      fetchSubmodules = true;
      sha256 = "sha256-6ompKXHM9Y5jc7UZ+yC00EhAivOC9gXk5HUMJsbPqpk=";
    };
    date = "2026-02-03";
  };
  experimental-kalico = {
    pname = "experimental-kalico";
    version = "107302c468c2e692e7bcb1e8c66032782c4ad555";
    src = fetchFromGitHub {
      owner = "KalicoCrew";
      repo = "kalico";
      rev = "107302c468c2e692e7bcb1e8c66032782c4ad555";
      fetchSubmodules = false;
      sha256 = "sha256-hNH6bFgSI3xIJQx5M1o7h5SMSP09mLdJwDmZtEn0p/E=";
    };
    date = "2026-01-04";
  };
  kalico = {
    pname = "kalico";
    version = "c70d21abd88757a6653f5081a125ea26be13c2be";
    src = fetchFromGitHub {
      owner = "KalicoCrew";
      repo = "kalico";
      rev = "c70d21abd88757a6653f5081a125ea26be13c2be";
      fetchSubmodules = false;
      sha256 = "sha256-dHYqWOv82IKRlRhpLuRbvH4S9TteK44IfA5sILxrnXw=";
    };
    date = "2026-01-31";
  };
  katapult = {
    pname = "katapult";
    version = "b0bf421069e2aab810db43d6e15f38817d981451";
    src = fetchFromGitHub {
      owner = "Arksine";
      repo = "katapult";
      rev = "b0bf421069e2aab810db43d6e15f38817d981451";
      fetchSubmodules = false;
      sha256 = "sha256-3b2PQfxb1jZtHM61QqHEGGBjljLfYqPEcJ95Sf3xCsg=";
    };
    date = "2025-11-15";
  };
  klipper = {
    pname = "klipper";
    version = "87ea2ff1cea4f1c1a05217e96a04dbe415f0b002";
    src = fetchFromGitHub {
      owner = "Klipper3d";
      repo = "klipper";
      rev = "87ea2ff1cea4f1c1a05217e96a04dbe415f0b002";
      fetchSubmodules = false;
      sha256 = "sha256-BxlIuRG6SpIqjI5BcMU5NgbXz0+sziMyLNWxc4B2QqI=";
    };
    date = "2026-02-05";
  };
  klipper-cartographer = {
    pname = "klipper-cartographer";
    version = "479f6ab607e61f632b9d20af5002afff725fc989";
    src = fetchFromGitHub {
      owner = "Cartographer3D";
      repo = "cartographer-klipper";
      rev = "479f6ab607e61f632b9d20af5002afff725fc989";
      fetchSubmodules = false;
      sha256 = "sha256-rHRSriWinZpwJzcTcYaFSpVRklX/3KNTt52Iby8GIhs=";
    };
    date = "2026-02-01";
  };
  klipper-cartographer-plugin = {
    pname = "klipper-cartographer-plugin";
    version = "v1.4.0";
    src = fetchFromGitHub {
      owner = "Cartographer3D";
      repo = "cartographer3d-plugin";
      rev = "v1.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-hkIRJVgfOREjWbKRvmoiX+Ez3lXb2JR51Y9U33ypS6w=";
    };
  };
  klipper-chopper-resonance-tuner = {
    pname = "klipper-chopper-resonance-tuner";
    version = "1f98212ca9dbfdf15d516115dd4c26e97b914a8d";
    src = fetchFromGitHub {
      owner = "MRX8024";
      repo = "chopper-resonance-tuner";
      rev = "1f98212ca9dbfdf15d516115dd4c26e97b914a8d";
      fetchSubmodules = false;
      sha256 = "sha256-KLWWjHgEmQ9yJD6uUgjYieY8S1Td1qB5SaWN1znAGDk=";
    };
    date = "2024-08-23";
  };
  klipper-ercf = {
    pname = "klipper-ercf";
    version = "fb9a6c7daaf881ab507368386e733a800b26f595";
    src = fetchFromGitHub {
      owner = "EtteGit";
      repo = "EnragedRabbitProject";
      rev = "fb9a6c7daaf881ab507368386e733a800b26f595";
      fetchSubmodules = false;
      sha256 = "sha256-Gwi0HiCIlTBQkHlFnmG0sZWB2xA1y5maJxF7VdfQMxU=";
    };
    date = "2022-09-02";
  };
  klipper-gcode_shell_command = {
    pname = "klipper-gcode_shell_command";
    version = "09a5d96b6339b9f0477b1dc58daadaf411e55416";
    src = fetchFromGitHub {
      owner = "dw-0";
      repo = "kiauh";
      rev = "09a5d96b6339b9f0477b1dc58daadaf411e55416";
      fetchSubmodules = false;
      sha256 = "sha256-vXCmvLhMRl0G/EA/MlD66Nai4KgrAtoSf25C6BE2FyA=";
    };
    date = "2026-02-03";
  };
  klipper-happy-hare = {
    pname = "klipper-happy-hare";
    version = "fe88af56f74ba3baf33ac0837377934f1d36dd3b";
    src = fetchFromGitHub {
      owner = "moggieuk";
      repo = "Happy-Hare";
      rev = "fe88af56f74ba3baf33ac0837377934f1d36dd3b";
      fetchSubmodules = false;
      sha256 = "sha256-mYI6eP5DLn20AOltkwtpwWwVprUgxfS98gMnlrrLjsY=";
    };
    date = "2026-01-24";
  };
  klipper-kamp = {
    pname = "klipper-kamp";
    version = "v1.1.2";
    src = fetchFromGitHub {
      owner = "kyleisah";
      repo = "Klipper-Adaptive-Meshing-Purging";
      rev = "v1.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-anBGjLtYlyrxeNVy1TEMcAGTVUFrGClLuoJZuo3xlDM=";
    };
  };
  klipper-klicky-probe = {
    pname = "klipper-klicky-probe";
    version = "ab86f91d47ac7353a0a7c7e0de26542dca00f63e";
    src = fetchFromGitHub {
      owner = "jlas1";
      repo = "Klicky-Probe";
      rev = "ab86f91d47ac7353a0a7c7e0de26542dca00f63e";
      fetchSubmodules = false;
      sha256 = "sha256-FKIBQnvDJdvgwPL3ekgx/6QbHPRuObEG307dlFk/fbY=";
    };
    date = "2025-02-10";
  };
  klipper-klippain-shaketune = {
    pname = "klipper-klippain-shaketune";
    version = "354ee4be6db218715239f7b9411c2c37fdea23dd";
    src = fetchFromGitHub {
      owner = "Frix-x";
      repo = "klippain-shaketune";
      rev = "354ee4be6db218715239f7b9411c2c37fdea23dd";
      fetchSubmodules = false;
      sha256 = "sha256-ztgLp8PUJafUBt/PdlGj5x7ER5vxw4uIfh3/3Cbl8Ps=";
    };
    date = "2026-01-16";
  };
  klipper-led_effect = {
    pname = "klipper-led_effect";
    version = "24d26c7208c7260a528b4438c7dbf0c279968c01";
    src = fetchFromGitHub {
      owner = "julianschill";
      repo = "klipper-led_effect";
      rev = "24d26c7208c7260a528b4438c7dbf0c279968c01";
      fetchSubmodules = false;
      sha256 = "sha256-Mv+xjT43SlP1x8tJ7ksfKdd2wfN2KZ4ydJmnjCj4V1M=";
    };
    date = "2026-01-23";
  };
  klipper-nevermore-controller = {
    pname = "klipper-nevermore-controller";
    version = "6c627d9b8bcd5dacdca27f335a5ccfb8a7093fbd";
    src = fetchFromGitHub {
      owner = "SanaaHamel";
      repo = "nevermore-controller";
      rev = "6c627d9b8bcd5dacdca27f335a5ccfb8a7093fbd";
      fetchSubmodules = false;
      sha256 = "sha256-O0Zkb7+mL5jFn8z+4pPyou7KqgW0v/1K4NpQuhxbHAU=";
    };
    date = "2025-11-02";
  };
  klipper-nevermore-max = {
    pname = "klipper-nevermore-max";
    version = "159df10e4f6015680107d1cbd10a3aab23dd5f18";
    src = fetchFromGitHub {
      owner = "nevermore3d";
      repo = "Nevermore_Max";
      rev = "159df10e4f6015680107d1cbd10a3aab23dd5f18";
      fetchSubmodules = false;
      sha256 = "sha256-uPTUlI2F697pDPw5HxU48dEUpBkgovb61ksXW1HRfLY=";
    };
    date = "2023-11-18";
  };
  klipper-screen = {
    pname = "klipper-screen";
    version = "35c26ba4d452043695d73fa8ec2acd25bbc8911d";
    src = fetchFromGitHub {
      owner = "jordanruthe";
      repo = "KlipperScreen";
      rev = "35c26ba4d452043695d73fa8ec2acd25bbc8911d";
      fetchSubmodules = false;
      sha256 = "sha256-DgpWoHCA7aU67Vq4Cc0nGghSTpu3IICBozEBdelvSZ4=";
    };
    date = "2026-02-04";
  };
  klipper-z-calibration = {
    pname = "klipper-z-calibration";
    version = "v1.1.3";
    src = fetchFromGitHub {
      owner = "protoloft";
      repo = "klipper_z_calibration";
      rev = "v1.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-WWP0LqhJ3ET4nxR8hVpq1uMOSK+CX7f3LXjOAZbRY8c=";
    };
  };
  klipper_tmc_autotune = {
    pname = "klipper_tmc_autotune";
    version = "f582d5f42b66df9ee1f087f2f1519ac241bbd5b1";
    src = fetchFromGitHub {
      owner = "andrewmcgr";
      repo = "klipper_tmc_autotune";
      rev = "f582d5f42b66df9ee1f087f2f1519ac241bbd5b1";
      fetchSubmodules = false;
      sha256 = "sha256-QbKmoqb780OC1bkQobCJlXwdWZqnF6uCkY8bv8Scuks=";
    };
    date = "2026-01-31";
  };
  libdatachannel_latest = {
    pname = "libdatachannel_latest";
    version = "366ef5b87e983eb51555fb9c5767a09f690a0099";
    src = fetchFromGitHub {
      owner = "paullouisageneau";
      repo = "libdatachannel";
      rev = "366ef5b87e983eb51555fb9c5767a09f690a0099";
      fetchSubmodules = true;
      sha256 = "sha256-xjrw0Ki99wy+XILk9OxtkamORxD9p7hrpUnrh3Kd3R8=";
    };
    date = "2026-02-01";
  };
  libjuice = {
    pname = "libjuice";
    version = "v1.6.2";
    src = fetchFromGitHub {
      owner = "paullouisageneau";
      repo = "libjuice";
      rev = "v1.6.2";
      fetchSubmodules = false;
      sha256 = "sha256-i+Hx0Qg9g35L5gg5OMVnitmQ84BnE+0IDXdvrLLdz8Y=";
    };
  };
  live555 = {
    pname = "live555";
    version = "2020.03.06";
    src = fetchTarball {
      url = "https://download.videolan.org/pub/contrib/live555/live.2020.03.06.tar.gz";
      sha256 = "sha256-UxunbrJC6UVlwexso/cuH9m+mUSf7WEPMLincUrqDWE=";
    };
  };
  mainsail = {
    pname = "mainsail";
    version = "fd5fa1218d3b072c12a1c16e3b0ba5ab4d4a9a74";
    src = fetchFromGitHub {
      owner = "mainsail-crew";
      repo = "mainsail";
      rev = "fd5fa1218d3b072c12a1c16e3b0ba5ab4d4a9a74";
      fetchSubmodules = false;
      sha256 = "sha256-DtHuLagBLmQiRdEmlaGYI/vDdNk+QMsz1bsqCcNqWC8=";
    };
    date = "2026-02-02";
  };
  mobileraker-companion = {
    pname = "mobileraker-companion";
    version = "1e866ae25278d574d38e779c1a31a9780a130761";
    src = fetchFromGitHub {
      owner = "Clon1998";
      repo = "mobileraker_companion";
      rev = "1e866ae25278d574d38e779c1a31a9780a130761";
      fetchSubmodules = false;
      sha256 = "sha256-RcMe/KSN72RUXXGiDkumRIyoXsn0RGRDRZk9mAZCZTU=";
    };
    date = "2026-01-10";
  };
  moonraker = {
    pname = "moonraker";
    version = "343bba4c604d182f5e778c33bcaefd9947d4677e";
    src = fetchFromGitHub {
      owner = "Arksine";
      repo = "moonraker";
      rev = "343bba4c604d182f5e778c33bcaefd9947d4677e";
      fetchSubmodules = false;
      sha256 = "sha256-C4IXD1Awa4nRRiL3igTBopu0pu5R8yfgwGbTZ0q8vIY=";
    };
    date = "2026-01-28";
  };
  python-networkmanager = {
    pname = "python-networkmanager";
    version = "2.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/python-networkmanager/python-networkmanager-2.2.tar.gz";
      sha256 = "sha256-3m65IdlKunVJ9CjtKzqkgqXVQ+y2lly6oPu1VasxudU=";
    };
  };
  python-scheduler = {
    pname = "python-scheduler";
    version = "0.8.8";
    src = fetchurl {
      url = "https://pypi.org/packages/source/s/scheduler/scheduler-0.8.8.tar.gz";
      sha256 = "sha256-RXWhLNJp5OSJZAmDb9kRVgy2P7djQ2DuYqovpOxJX/0=";
    };
  };
  python-sqlalchemy-cockroachdb = {
    pname = "python-sqlalchemy-cockroachdb";
    version = "2.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/s/sqlalchemy-cockroachdb/sqlalchemy-cockroachdb-2.0.2.tar.gz";
      sha256 = "sha256-EZdW65BYVdahE0W5nP6FMDGj/lmKnEvzWo3ayfif6Mw=";
    };
  };
  spoolman = {
    pname = "spoolman";
    version = "v0.23.1";
    src = fetchurl {
      url = "https://github.com/Donkie/Spoolman/releases/download/v0.23.1/spoolman.zip";
      sha256 = "sha256-v64qELJ33WdKvZ7+yFwELI1vRwChVa+VHAlg2z9iYYU=";
    };
  };
}
