# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  attic = {
    pname = "attic";
    version = "5fc1b918c12c2658603f6d88a75aa4a2e74080df";
    src = fetchFromGitHub {
      owner = "ByteZ1337";
      repo = "attic";
      rev = "5fc1b918c12c2658603f6d88a75aa4a2e74080df";
      fetchSubmodules = false;
      sha256 = "sha256-1koNX1T45G/Qz8xPFE7lR/awpkiJUY0omL/ofTYd60I=";
    };
  };
  s5cmd = {
    pname = "s5cmd";
    version = "54d6a8a955688f07e5acc40d61f9c42ceac6c33b";
    src = fetchFromGitHub {
      owner = "peak";
      repo = "s5cmd";
      rev = "54d6a8a955688f07e5acc40d61f9c42ceac6c33b";
      fetchSubmodules = false;
      sha256 = "sha256-2uEA7Szi3vPI851CiuR1G2n+0RTPyKG6erWzjtT+L0U=";
    };
    date = "2025-06-13";
  };
  tfenv = {
    pname = "tfenv";
    version = "6ae6519d59a9489bf3abb23bc3eda8b46eaea148";
    src = fetchFromGitHub {
      owner = "tfutils";
      repo = "tfenv";
      rev = "6ae6519d59a9489bf3abb23bc3eda8b46eaea148";
      fetchSubmodules = false;
      sha256 = "sha256-9ECEVT5OczsTTbL64v25mmwu1IPySwSlE5atWN0Q4QA=";
    };
    date = "2026-04-25";
  };
  transmissionic = {
    pname = "transmissionic";
    version = "v1.8.0";
    src = fetchurl {
      url = "https://github.com/6c65726f79/Transmissionic/releases/download/v1.8.0/Transmissionic-webui-v1.8.0.zip";
      sha256 = "sha256-IhbJCv9SWjLspJYv6dBKrooGk+vA7sq1N3WzMne6PEw=";
    };
  };
}
