# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  s5cmd = {
    pname = "s5cmd";
    version = "54d6a8a955688f07e5acc40d61f9c42ceac6c33b";
    src = fetchFromGitHub {
      owner = "peak";
      repo = "s5cmd";
      rev = "54d6a8a955688f07e5acc40d61f9c42ceac6c33b";
      fetchSubmodules = false;
      sha256 = "sha256-2uEA7Szi3vPI851CiuR1G2n+0RTPyKG6erWzjtT+L0U=";
    };
    date = "2025-06-13";
  };
  tfenv = {
    pname = "tfenv";
    version = "c8eb402135bf6fbcd2809f6cdbf7ea1113de6e54";
    src = fetchFromGitHub {
      owner = "tfutils";
      repo = "tfenv";
      rev = "c8eb402135bf6fbcd2809f6cdbf7ea1113de6e54";
      fetchSubmodules = false;
      sha256 = "sha256-wyfjgX774K95HpD96qT7KzHMeqY7JYCvp6gY5eqhlt8=";
    };
    date = "2025-07-11";
  };
  transmissionic = {
    pname = "transmissionic";
    version = "v1.8.0";
    src = fetchurl {
      url = "https://github.com/6c65726f79/Transmissionic/releases/download/v1.8.0/Transmissionic-webui-v1.8.0.zip";
      sha256 = "sha256-IhbJCv9SWjLspJYv6dBKrooGk+vA7sq1N3WzMne6PEw=";
    };
  };
}
