# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.
{ pkgs, lib }:

let
  inherit (pkgs.stdenv) isDarwin isLinux isi686 isx86_64 isAarch32 isAarch64;
  vscode-utils = pkgs.vscode-utils;
  merge = lib.attrsets.recursiveUpdate;
in
merge
  (merge
    (merge
      (merge
      {
        "4ops"."packer" = vscode-utils.extensionFromVscodeMarketplace {
          name = "packer";
          publisher = "4ops";
          version = "0.3.0";
          sha256 = "0my10qn06w5sd5cmwkghsqnn6d91f346yv9i22949s3ysz2x72v9";

        };
        "arrterian"."nix-env-selector" = vscode-utils.extensionFromVscodeMarketplace {
          name = "nix-env-selector";
          publisher = "arrterian";
          version = "1.0.11";
          sha256 = "113zx78c3219knw4qa04242404n32vnk9rb6a3ynz41dgwh1mbbl";

        };
        "bbenoist"."nix" = vscode-utils.extensionFromVscodeMarketplace {
          name = "nix";
          publisher = "bbenoist";
          version = "1.0.1";
          sha256 = "0zd0n9f5z1f0ckzfjr38xw2zzmcxg1gjrava7yahg5cvdcw6l35b";

        };
        "catppuccin"."catppuccin-vsc" = vscode-utils.extensionFromVscodeMarketplace {
          name = "catppuccin-vsc";
          publisher = "catppuccin";
          version = "3.17.0";
          sha256 = "167nb7s9m999j98frfr0xyxhybqadyhg2535vlnrbc04f2qxpl5r";

        };
        "christian-kohler"."path-intellisense" = vscode-utils.extensionFromVscodeMarketplace {
          name = "path-intellisense";
          publisher = "christian-kohler";
          version = "2.10.0";
          sha256 = "06x9ksl4bghfpxh4n65d1d7dr11spl140p9ch4mc01nrdibgckbc";

        };
        "coolbear"."systemd-unit-file" = vscode-utils.extensionFromVscodeMarketplace {
          name = "systemd-unit-file";
          publisher = "coolbear";
          version = "1.0.6";
          sha256 = "0sc0zsdnxi4wfdlmaqwb6k2qc21dgwx6ipvri36x7agk7m8m4736";

        };
        "davidanson"."vscode-markdownlint" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-markdownlint";
          publisher = "davidanson";
          version = "0.60.0";
          sha256 = "18fw4snqfa7bys04r8748vv6x7gfaq2bqvhqm9x3z1fsf7mimv06";

        };
        "dbaeumer"."vscode-eslint" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-eslint";
          publisher = "dbaeumer";
          version = "3.0.10";
          sha256 = "02snfjlrgs4i9svyhipkirvwj9vqfylswzvfizk00hf8fk39wn8i";

        };
        "donjayamanne"."githistory" = vscode-utils.extensionFromVscodeMarketplace {
          name = "githistory";
          publisher = "donjayamanne";
          version = "0.6.20";
          sha256 = "0x9q7sh5l1frpvfss32ypxk03d73v9npnqxif4fjwcfwvx5mhiww";

        };
        "eamodio"."gitlens" = vscode-utils.extensionFromVscodeMarketplace {
          name = "gitlens";
          publisher = "eamodio";
          version = "17.1.1";
          sha256 = "07lyd3s5g6w5piglqbsm808f620j1mc8lwbr4cm41gvpnkhnln46";

        };
        "editorconfig"."editorconfig" = vscode-utils.extensionFromVscodeMarketplace {
          name = "editorconfig";
          publisher = "editorconfig";
          version = "0.17.2";
          sha256 = "1s0a2zgxk6qxl6lzw6klkn8xhsxk0l87vcbms2k8535kvscbwbay";

        };
        "ericadamski"."carbon-now-sh" = vscode-utils.extensionFromVscodeMarketplace {
          name = "carbon-now-sh";
          publisher = "ericadamski";
          version = "1.2.0";
          sha256 = "0an0vvxz63ckn65xf85yv8z9mzd9niwfl1nxmkhh6w5g5sskhllc";

        };
        "golang"."go" = vscode-utils.extensionFromVscodeMarketplace {
          name = "go";
          publisher = "golang";
          version = "0.46.1";
          sha256 = "1fx6il5mpl6z2y68s63ssy28k8hhkj998r3rpajpckqnygm85527";

        };
        "ipedrazas"."kubernetes-snippets" = vscode-utils.extensionFromVscodeMarketplace {
          name = "kubernetes-snippets";
          publisher = "ipedrazas";
          version = "0.1.9";
          sha256 = "0gf1m9vppcsdbvdsx2k0a9xj2cfqbbm8b4iw7v8xgn4y2k6w8lq6";

        };
        "ivory-lab"."jenkinsfile-support" = vscode-utils.extensionFromVscodeMarketplace {
          name = "jenkinsfile-support";
          publisher = "ivory-lab";
          version = "1.1.0";
          sha256 = "0n30kkla6dwdzgdimqy4hkqrxhpvrgfnd2zf7c3zx328hhbznaky";

        };
        "jnoortheen"."nix-ide" = vscode-utils.extensionFromVscodeMarketplace {
          name = "nix-ide";
          publisher = "jnoortheen";
          version = "0.4.18";
          sha256 = "16n9nzm9wdmhrcxhlw0d9a8195w0m8nh4gzbac4432jw8mkvbk5r";

        };
        "jq-syntax-highlighting"."jq-syntax-highlighting" = vscode-utils.extensionFromVscodeMarketplace {
          name = "jq-syntax-highlighting";
          publisher = "jq-syntax-highlighting";
          version = "0.0.2";
          sha256 = "0q91mr6a6935wnka5iga97lv78g19dlj2rz6qg3ki6w3kdlvw2h7";

        };
        "likec4"."likec4-vscode" = vscode-utils.extensionFromVscodeMarketplace {
          name = "likec4-vscode";
          publisher = "likec4";
          version = "1.31.0";
          sha256 = "1p1mk1lxl5b57z32v6yn39ag0ap6fv6i3dl89xj38nnyhymyzvxv";

        };
        "lunuan"."kubernetes-templates" = vscode-utils.extensionFromVscodeMarketplace {
          name = "kubernetes-templates";
          publisher = "lunuan";
          version = "1.3.1";
          sha256 = "0bjyx9ri7fl68ryy0icn1lc3r8gxkpwaxhh900ij8xfvabqvcx6m";

        };
        "mads-hartmann"."bash-ide-vscode" = vscode-utils.extensionFromVscodeMarketplace {
          name = "bash-ide-vscode";
          publisher = "mads-hartmann";
          version = "1.43.0";
          sha256 = "157n2m9dhb26q6yvd16rb5yi2k8k7f7v6vd03vyvvy0rhv7454i2";

        };
        "marus25"."cortex-debug" = vscode-utils.extensionFromVscodeMarketplace {
          name = "cortex-debug";
          publisher = "marus25";
          version = "1.12.1";
          sha256 = "1kbw93915a2ag3rgddyz4wnlifl6f2m9cxbxqqghfs341f1vm0la";

        };
        "mcu-debug"."debug-tracker-vscode" = vscode-utils.extensionFromVscodeMarketplace {
          name = "debug-tracker-vscode";
          publisher = "mcu-debug";
          version = "0.0.15";
          sha256 = "0wlz089z91my82kygv7kmip0nfkmgczcyl5h1hpxwzvb5ji0rvns";

        };
        "mcu-debug"."memory-view" = vscode-utils.extensionFromVscodeMarketplace {
          name = "memory-view";
          publisher = "mcu-debug";
          version = "0.0.25";
          sha256 = "0iqfblx5ayhpf1gj3szf3hn6145yqmkgqn18bhi5l9l7h8qkgjad";

        };
        "mcu-debug"."peripheral-viewer" = vscode-utils.extensionFromVscodeMarketplace {
          name = "peripheral-viewer";
          publisher = "mcu-debug";
          version = "1.4.6";
          sha256 = "1a499vnjmdxlh98h4c82dfrkafak3rj9h0wiwqrbibd0xcmq2mby";

        };
        "mcu-debug"."rtos-views" = vscode-utils.extensionFromVscodeMarketplace {
          name = "rtos-views";
          publisher = "mcu-debug";
          version = "0.0.7";
          sha256 = "1nhxhiq6a5rckfy9pqdkjbfq06c4xzlaqm4a5rq5r26a9rhh1wsn";

        };
        "mkhl"."direnv" = vscode-utils.extensionFromVscodeMarketplace {
          name = "direnv";
          publisher = "mkhl";
          version = "0.17.0";
          sha256 = "1n2qdd1rspy6ar03yw7g7zy3yjg9j1xb5xa4v2q12b0y6dymrhgn";

        };
        "ms-kubernetes-tools"."vscode-kubernetes-tools" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-kubernetes-tools";
          publisher = "ms-kubernetes-tools";
          version = "1.3.20";
          sha256 = "195l18ln3rylximnrbp86zv7sqc9p8mav4iqxbc0vyx7508rqwpk";

        };
        "ms-python"."vscode-pylance" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-pylance";
          publisher = "ms-python";
          version = "2025.4.1";
          sha256 = "0ldgacr9yqaj9zmxnj5rkkamr1044cf9rfjqsv7qkvpyw4f397ax";

        };
        "ms-vscode-remote"."remote-ssh" = vscode-utils.extensionFromVscodeMarketplace {
          name = "remote-ssh";
          publisher = "ms-vscode-remote";
          version = "0.120.0";
          sha256 = "0p8rx867pdwyzx1bcjf069zzi8nfvhb3bjv7q3v8dd43l4n2dmhg";

        };
        "ms-vscode-remote"."remote-ssh-edit" = vscode-utils.extensionFromVscodeMarketplace {
          name = "remote-ssh-edit";
          publisher = "ms-vscode-remote";
          version = "0.87.0";
          sha256 = "1qqsnzn9z11jr72n7cl0ab6i9mv49c0ijcp699zbglv5092gmrf9";

        };
        "natqe"."reload" = vscode-utils.extensionFromVscodeMarketplace {
          name = "reload";
          publisher = "natqe";
          version = "0.0.7";
          sha256 = "1bpzv7pg80ly31l2fyi7lbdyi2w71x7w5g3p63017hlsi3ny6h4g";

        };
        "nicolasvuillamy"."vscode-groovy-lint" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-groovy-lint";
          publisher = "nicolasvuillamy";
          version = "3.3.1";
          sha256 = "1gha2rn643bz2pydr7npyrl9p79zlxqns4qmq4cdmp8py2jq92c3";

        };
        "pkief"."material-icon-theme" = vscode-utils.extensionFromVscodeMarketplace {
          name = "material-icon-theme";
          publisher = "pkief";
          version = "5.23.0";
          sha256 = "09xcjqfqjrzzy4d9vlni52zbg3c3ffmp9sbmjjhz5a61sam8xscy";

        };
        "plorefice"."devicetree" = vscode-utils.extensionFromVscodeMarketplace {
          name = "devicetree";
          publisher = "plorefice";
          version = "0.1.1";
          sha256 = "0yfz6rgmh9j9bq7ahcjxphj74jd8rnnlg355vffdy8xfqdirxp5r";

        };
        "probe-rs"."probe-rs-debugger" = vscode-utils.extensionFromVscodeMarketplace {
          name = "probe-rs-debugger";
          publisher = "probe-rs";
          version = "0.24.2";
          sha256 = "0d3b4xhmf6a0xcjn5g3npmnvj6c9sizhzm8acm7gdcqskh7kjsyl";

        };
        "redhat"."vscode-commons" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-commons";
          publisher = "redhat";
          version = "0.0.6";
          sha256 = "1b8nlhbrsg3kj27f1kgj8n5ak438lcfq5v5zlgf1hzisnhmcda5n";

        };
        "roscop"."activefileinstatusbar" = vscode-utils.extensionFromVscodeMarketplace {
          name = "activefileinstatusbar";
          publisher = "roscop";
          version = "1.0.3";
          sha256 = "0sbs3138hnpg4x226gyz94161i0sw7pdi4f2dcyxxwwbs86lwqp4";

        };
        "systemticks"."c4-dsl-extension" = vscode-utils.extensionFromVscodeMarketplace {
          name = "c4-dsl-extension";
          publisher = "systemticks";
          version = "3.7.1";
          sha256 = "0kn7k70l7fcw562z1ii7cpxb1zbigqh0pjsqvbnknylhj85h096j";

        };
        "tamasfe"."even-better-toml" = vscode-utils.extensionFromVscodeMarketplace {
          name = "even-better-toml";
          publisher = "tamasfe";
          version = "0.21.2";
          sha256 = "0208cms054yj2l8pz9jrv3ydydmb47wr4i0sw8qywpi8yimddf11";

        };
        "tim-koehler"."helm-intellisense" = vscode-utils.extensionFromVscodeMarketplace {
          name = "helm-intellisense";
          publisher = "tim-koehler";
          version = "0.15.0";
          sha256 = "1sl333j2c0xp2ab8a2f0nncanhf4qs901wnvvbgwhkk07gd1fpaf";

        };
        "whi-tw"."klipper-config-syntax" = vscode-utils.extensionFromVscodeMarketplace {
          name = "klipper-config-syntax";
          publisher = "whi-tw";
          version = "0.2.2";
          sha256 = "0v52p7s5sn3nv2h138wakc2zikdi00dqq98lrd3c0r6607dhab21";

        };
        "zixuanwang"."linkerscript" = vscode-utils.extensionFromVscodeMarketplace {
          name = "linkerscript";
          publisher = "zixuanwang";
          version = "1.0.4";
          sha256 = "0mfna6xypzfwsrmfzx898pc76ddfn4n8yr8l4d8gbhcyqyj5y3zp";

        };
      }
        (lib.attrsets.optionalAttrs (isLinux && (isi686 || isx86_64)) {
          "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
            name = "terraform";
            publisher = "hashicorp";
            version = "2.34.4";
            sha256 = "1ppyvdmj2lvixhyzyadrbhxhd7f8hln68x058bxj943zx2rs27wa";
            arch = "linux-x64";

          };
          "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
            name = "python";
            publisher = "ms-python";
            version = "2025.6.1";
            sha256 = "1n3jnmwgddc014m35nfac5kz06hp9qr2plimxdla7lhyz0vhlgyx";
            arch = "linux-x64";

          };
          "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-xml";
            publisher = "redhat";
            version = "0.29.0";
            sha256 = "0dvkrsc4v6pxran4ygy5b0pg9x53a6b6w0gp7l645zf26nj16wqn";
            arch = "linux-x64";

          };
          "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
            name = "rust-analyzer";
            publisher = "rust-lang";
            version = "0.3.2474";
            sha256 = "0s9bds81m6i9wmmh6rii5110ic0fza6fw0rbrkn22d9m8mx0f2aa";
            arch = "linux-x64";

          };
        }))
      (lib.attrsets.optionalAttrs (isLinux && (isAarch32 || isAarch64)) {
        "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
          name = "terraform";
          publisher = "hashicorp";
          version = "2.34.4";
          sha256 = "1hhvsnivamvi9ll4q9aqlrrdkx4z542qmmnb8b43zb8n1dc6zg21";
          arch = "linux-arm64";

        };
        "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
          name = "python";
          publisher = "ms-python";
          version = "2025.6.1";
          sha256 = "0fyqrii331q4zcfl0ga43yj77882711z3pjxkv9a7cz846sgv0dq";
          arch = "linux-arm64";

        };
        "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
          name = "rust-analyzer";
          publisher = "rust-lang";
          version = "0.3.2474";
          sha256 = "1khs9745la3xk5lw493nlfnv3dvbj3hna44n14cisyj0p7va08r5";
          arch = "linux-arm64";

        };
      }))
    (lib.attrsets.optionalAttrs (isDarwin && (isi686 || isx86_64)) {
      "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
        name = "terraform";
        publisher = "hashicorp";
        version = "2.34.4";
        sha256 = "1piy2bp78hny2zcbwms8i06jl5i72p8mjhx462w85zbdim9i25y1";
        arch = "darwin-x64";

      };
      "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
        name = "python";
        publisher = "ms-python";
        version = "2025.6.1";
        sha256 = "1rwk0hhck3vdwk698ndcdzaajrs1r7vwhhk4p9wv91svr81cplj4";
        arch = "darwin-x64";

      };
      "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
        name = "vscode-xml";
        publisher = "redhat";
        version = "0.29.0";
        sha256 = "1qzq3b4a66iq6xci6im7kb2fpjxdr2vvw2vshd47kvjxxb613ybc";
        arch = "darwin-x64";

      };
      "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
        name = "rust-analyzer";
        publisher = "rust-lang";
        version = "0.3.2474";
        sha256 = "03l4ykvrv6lasvawmb34gi7ypd2zx4biw9yzin8359xv766i8108";
        arch = "darwin-x64";

      };
    }))
  (lib.attrsets.optionalAttrs (isDarwin && (isAarch32 || isAarch64)) {
    "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
      name = "terraform";
      publisher = "hashicorp";
      version = "2.34.4";
      sha256 = "1pw3ql7ppi8ni9p4wlg2wvi0l0ablnnfq154qr19v1z4mvp3fdc1";
      arch = "darwin-arm64";

    };
    "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
      name = "python";
      publisher = "ms-python";
      version = "2025.6.1";
      sha256 = "1hrkknw22q08xc3aqi1m0g07x9llvvz955w02xqgg6ypjkf38ksh";
      arch = "darwin-arm64";

    };
    "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
      name = "vscode-xml";
      publisher = "redhat";
      version = "0.29.0";
      sha256 = "0b8kb5s4xjw3nh48w665j069hf4f46cv5564kyrzhwd27735cx2j";
      arch = "darwin-arm64";

    };
    "rust-lang"."rust-analyzer" = vscode-utils.extensionFromVscodeMarketplace {
      name = "rust-analyzer";
      publisher = "rust-lang";
      version = "0.3.2474";
      sha256 = "1gpmi2kpk9xymhqn1lkrs1cqjlj5f60k9nfxbdqhv99fxflsslvf";
      arch = "darwin-arm64";

    };
  })
