# Kindly taken from https://github.com/nuxencs/recyclarr-configs/blob/master/includes/radarr-qp.yml
quality_profiles:
  - name: Golden Popcorn
    reset_unmatched_scores:
      enabled: true
    upgrade:
      allowed: true
      until_quality: WEB/Bluray 1080p
      until_score: 10000
    min_format_score: 10
    quality_sort: top
    qualities:
      - name: Remux-1080p
        enabled: false
      - name: WEB/Bluray 1080p
        qualities:
          - Bluray-1080p
          - WEBDL-1080p
          - WEBRip-1080p

  - name: Streaming Optimized
    reset_unmatched_scores:
      enabled: true
    upgrade:
      allowed: true
      until_quality: WEB/Bluray 1080p
      until_score: 10000
    min_format_score: 1000
    score_set: sqp-1-1080p
    quality_sort: top
    qualities:
      - name: Remux-1080p
        enabled: false
      - name: WEB/Bluray 1080p
        qualities:
          - Bluray-1080p
          - WEBDL-1080p
          - WEBRip-1080p