# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  wsl-kernel-6-6-87-2 = {
    pname = "wsl-kernel-6-6-87-2";
    version = "linux-msft-wsl-6.6.87.2";
    src = fetchFromGitHub {
      owner = "microsoft";
      repo = "WSL2-Linux-Kernel";
      rev = "linux-msft-wsl-6.6.87.2";
      fetchSubmodules = false;
      sha256 = "sha256-UYPqnn605nPplLqDnEKGZ625K+AahOqy3D1ENQE7d/8=";
    };
    tag = "6.6.87.2";
  };
  wsl-xanmod-lts = {
    pname = "wsl-xanmod-lts";
    version = "6.18.34-locietta-WSL2-xanmod1.1-lts";
    src = fetchFromGitHub {
      owner = "Locietta";
      repo = "xanmod-kernel-WSL2";
      rev = "6.18.34-locietta-WSL2-xanmod1.1-lts";
      fetchSubmodules = false;
      sha256 = "sha256-blGNYfqpqMqdwUyowWApq62Jg0Lrmx0HaHrlkM/zcE0=";
    };
  };
  xanmod-lts = {
    pname = "xanmod-lts";
    version = "6.18.34-xanmod1";
    src = fetchgit {
      url = "https://gitlab.com/xanmod/linux.git";
      rev = "6.18.34-xanmod1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lDHBPXY716pDs+Hr6qS7zPJPEN1shMSK/V32SBLv4/s=";
    };
  };
}
