# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  btt-linux-rockchip = {
    pname = "btt-linux-rockchip";
    version = "bpi-rk-6.1-rkr5.1";
    src = fetchFromGitHub {
      owner = "bigtreetech";
      repo = "linux-rockchip";
      rev = "bpi-rk-6.1-rkr5.1";
      fetchSubmodules = false;
      sha256 = "sha256-nkDkV6A+fko5egnvKSCJryRA/upwgBtQUB3nCH/Wcxs=";
    };
  };
  uboot = {
    pname = "uboot";
    version = "v2026.10";
    src = fetchFromGitHub {
      owner = "u-boot";
      repo = "u-boot";
      rev = "v2026.10";
      fetchSubmodules = false;
      sha256 = "sha256-BXIpyAY+uKSohrdG4BxAo0zq4CYmh2z9rFw1jA7Yu8s=";
    };
  };
  uboot-2024-10 = {
    pname = "uboot-2024-10";
    version = "v2024.10";
    src = fetchFromGitHub {
      owner = "u-boot";
      repo = "u-boot";
      rev = "v2024.10";
      fetchSubmodules = false;
      sha256 = "sha256-UPy7XM1NGjbEt+pQr4oQrzD7wWWEtYDOPWTD+CNYMHs=";
    };
  };
}
