[uboot]
fetch.github = "u-boot/u-boot"
src.manual = "v2026.10"

[uboot-2024-10]
fetch.github = "u-boot/u-boot"
src.manual = "v2024.10"

[btt-linux-rockchip]
fetch.github = "bigtreetech/linux-rockchip"
src.manual = "bpi-rk-6.1-rkr5.1"
