# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  libcamera = {
    pname = "libcamera";
    version = "bfd68f786964636b09f8122e6c09c230367390e7";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "bfd68f786964636b09f8122e6c09c230367390e7";
      fetchSubmodules = false;
      sha256 = "sha256-4rNV9TMDvVpMBmgeRftO51ptOyHh4QOgoyZ6F/Iwdnw=";
    };
    date = "2025-09-01";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "0a6609ed3304100fda37571ac5a24e5afe0774cc";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "0a6609ed3304100fda37571ac5a24e5afe0774cc";
      fetchSubmodules = false;
      sha256 = "sha256-OdtHXEf9rGm/9/4iRZuIiXA7zbcPXpoZQG5CSrFgXdw=";
    };
    date = "2025-09-29";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "b7c1bdb7bcf2d4118d7ab671b007a1fc741de311";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "b7c1bdb7bcf2d4118d7ab671b007a1fc741de311";
      fetchSubmodules = false;
      sha256 = "sha256-GQzL8IVa5qZj6Qgy28+oIGVVLYjkvjJJX8HZAY+PlDg=";
    };
    date = "2025-10-03";
  };
}
