# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  hls-js = {
    pname = "hls-js";
    version = "v1.6.16";
    src = fetchurl {
      url = "https://github.com/video-dev/hls.js/releases/download/v1.6.16/release.zip";
      sha256 = "sha256-Ccgnlp5wLoK+aU2oDb8W299f9oGcM6N0sXV+G8CttFg=";
    };
  };
  libcamera = {
    pname = "libcamera";
    version = "26bfadc66e8d7f727a993fe58174217b8a96f7f9";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "26bfadc66e8d7f727a993fe58174217b8a96f7f9";
      fetchSubmodules = false;
      sha256 = "sha256-U4cjIbZ9Z4sL+sE6qGWUalBeruPME6kzBZpHNGjKlJU=";
    };
    date = "2026-04-29";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "9d41d4b7a83dadc0be500f0b53de506ba4418989";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "9d41d4b7a83dadc0be500f0b53de506ba4418989";
      fetchSubmodules = false;
      sha256 = "sha256-WXh8Y6vCUl+2TeC73SSZCT6HVeHNgWSLKJNR/Mnp0OQ=";
    };
    date = "2026-05-27";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "v1.19.0";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "v1.19.0";
      fetchSubmodules = false;
      sha256 = "sha256-awNC1CITsG3hIibI2RaM6VgzYkEORopA13END+l0n+o=";
    };
  };
  mediamtx-rpicamera = {
    pname = "mediamtx-rpicamera";
    version = "v2.6.0";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx-rpicamera";
      rev = "v2.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-opTE58PMhG0k8Y8zAeheAb6aRN0Qq+ozMDPx1yyiHT0=";
    };
  };
}
