# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  libcamera = {
    pname = "libcamera";
    version = "bfd68f786964636b09f8122e6c09c230367390e7";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "bfd68f786964636b09f8122e6c09c230367390e7";
      fetchSubmodules = false;
      sha256 = "sha256-4rNV9TMDvVpMBmgeRftO51ptOyHh4QOgoyZ6F/Iwdnw=";
    };
    date = "2025-09-01";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "24906da670e9f2468ac18f2885218b2ba3491a20";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "24906da670e9f2468ac18f2885218b2ba3491a20";
      fetchSubmodules = false;
      sha256 = "sha256-yyZlZSpYYt1DLAI7rW8lnpR6p9HnqcV6SrEJcAyS6Aw=";
    };
    date = "2025-10-24";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "d4741b7d686a8590a9cfa42c108e1e9f1b0e9f29";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "d4741b7d686a8590a9cfa42c108e1e9f1b0e9f29";
      fetchSubmodules = false;
      sha256 = "sha256-GMO7NQ05XZ+G//xhZeQhNJAxQuSRXGY6hiIOJAFrvAc=";
    };
    date = "2025-11-07";
  };
}
