# Kindly taken from https://github.com/nuxencs/recyclarr-configs/blob/master/includes/sonarranime-qp.yml
quality_profiles:
  - name: Anime
    reset_unmatched_scores:
      enabled: true
    upgrade:
      allowed: true
      until_quality: Bluray-1080p
      until_score: 10000
    min_format_score: 100
    score_set: anime-sonarr
    quality_sort: top
    qualities:
      - name: Bluray-1080p
      - name: Anime-1080p/720p
        qualities:
          - WEBDL-1080p
          - WEBRip-1080p
          - HDTV-1080p
          - WEBDL-720p
          - WEBRip-720p
          - HDTV-720p
          - DVD